updated

diff --git a/week02/project/runtests b/week02/project/runtests
--- a/week02/project/runtests
+++ b/week02/project/runtests
@@ -35,36 +35,45 @@ compare() {
     eval $ctl > ctl.$TEMP.out
     eval $exp > exp.$TEMP.out
 
-    diff "$ctl_out" "$exp_out"
+    #echo "----------------"; cat exp.$TEMP.out; echo "----------------"
+
+    diff -Z "$ctl_out" "$exp_out"
 
     cleanup
 }
 
 status "Searching"
 
-dir=$(dirname $(find . -name mycat.c))
+path=$(find . -name mycat.c)
+
+if [ ${path:-x} = "x" ]; then
+    printf "couldn't find files\n" 1>&2
+    exit 1
+fi
+
+dir=$(dirname $path)
 
 printf "Found files in %s\n" "$dir"
 
 status "Building"
-(
-    cd $dir
-    make clean
-    make
-)
+pushd $dir
+make clean
+make || exit 1
+popd
 
 compare "$CDIR/hello" "$dir/hello"
 compare "$CDIR/printcl" "$dir/printcl"
 compare "$CDIR/printcl aaa bbb" "$dir/printcl aaa bbb"
 compare "$CDIR/readfile readfile.txt" "$dir/readfile readfile.txt"
+
 compare "echo hi there | $CDIR/mycat" "echo hi there | $dir/mycat"
 compare "$CDIR/mycat readfile.txt" "$dir/mycat readfile.txt"
 compare "$CDIR/mycat readfile.txt readfile.txt" "$dir/mycat readfile.txt readfile.txt"
 compare "$CDIR/mycat lotsawords.txt" "$dir/mycat lotsawords.txt"
 compare "$CDIR/mycat lotsawords.txt readfile.txt lotsawords.txt" "$dir/mycat lotsawords.txt readfile.txt lotsawords.txt"
+
 compare "echo hi there | $CDIR/yell" "echo hi there | $dir/yell"
 compare "$CDIR/yell readfile.txt" "$dir/yell readfile.txt"
-#compare "$CDIR/yell readfile.txt readfile.txt" "$dir/yell readfile.txt readfile.txt"
-#compare "$CDIR/yell lotsawords.txt" "$dir/yell lotsawords.txt"
-#compare "$CDIR/yell lotsawords.txt readfile.txt lotsawords.txt" "$dir/yell lotsawords.txt readfile.txt lotsawords.txt"
-
+compare "$CDIR/yell readfile.txt readfile.txt" "$dir/yell readfile.txt readfile.txt"
+compare "$CDIR/yell lotsawords.txt" "$dir/yell lotsawords.txt"
+compare "$CDIR/yell lotsawords.txt readfile.txt lotsawords.txt" "$dir/yell lotsawords.txt readfile.txt lotsawords.txt"
